### ISSUE TITLE
[Security Issue] Remove API Keys

### ISSUE THREAD

**Issue by leovarmak** [team-anything/HelpOff#9]
The API Keys are visible in the code. Its not advised to store it openly. 

Shall I send a PR after removing the API Keys ?

**Comment by inishchith** [comment]
> The API Keys are visible in the code. Its not advised to store it openly .

Damn , totally forgot .

@leovarmak sure go ahead!

**Comment by leovarmak** [comment]
I am unable to send a pull request. It says I don't have enough permissions 🤔

**Comment by inishchith** [comment]
>  I am unable to send a pull request. It says I don't have enough permissions 🤔

you'e trying to commit straight to this repo IMO.

you need to : 
> fork
make changes to your fork
send in a PR here

**Comment by leovarmak** [comment]
Haha. I know how to send a PR 😅 . There was a issue with my account
Sent now!

**Comment by inishchith** [comment]
#10
